baseURL = "http://tomokazu518.github.io/public"
languageCode = "ja"
title = "Tomokazu NOMURA"
theme = "hugo-geekdoc"
googleAnalytics = "G-RTN2PJF998"
publishDir = "docs"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
